# Generated by Django 4.1.2 on 2022-10-28 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, verbose_name='Status Tools')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('trademark', models.CharField(max_length=20, verbose_name='Trademark')),
                ('dimension', models.CharField(max_length=20, verbose_name='Dimension')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('status_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.statustools', verbose_name='Status Tool')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
