# Generated by Django 4.1.2 on 2023-05-08 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
    ]
