# Generated by Django 4.1.2 on 2022-10-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.department')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='client.person')),
                ('nit', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nit')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.country')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.department')),
            ],
            options={
                'abstract': False,
            },
            bases=('client.person',),
        ),
    ]
