# Generated by Django 4.1.2 on 2022-10-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mesurement_units',
            new_name='measurement_units',
        ),
    ]
