# Generated by Django 4.1.2 on 2022-10-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_mesurement_units_item_measurement_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurement_uits',
            new_name='Measurement_units',
        ),
    ]
