# Generated by Django 4.1.2 on 2022-10-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id_emloyee',
            new_name='emloyee_id',
        ),
    ]
