# Generated by Django 4.1.2 on 2022-10-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('order', '0002_rename_id_emloyee_order_emloyee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emloyee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
    ]
