# Generated by Django 4.1.2 on 2022-12-04 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_emloyee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='emloyee_id',
            new_name='employee_id',
        ),
    ]
