# Generated by Django 4.1.2 on 2023-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_emloyee_id_order_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocess',
            name='id_process',
            field=models.CharField(default=0, max_length=20, verbose_name='Order Process'),
            preserve_default=False,
        ),
    ]
