# Generated by Django 4.1.2 on 2023-05-02 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('employee', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_description', models.CharField(max_length=30, verbose_name='Status Description')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(max_length=30, verbose_name='Quote Number')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('client_id', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client')),
                ('document_employee', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee Document')),
                ('item_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='Item Id')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.statusquote', verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
