# Generated by Django 4.1.2 on 2022-10-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='nit_client',
            new_name='client_id',
        ),
    ]
