# Generated by Django 4.1.2 on 2022-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_rename_nit_client_quote_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Amount'),
        ),
    ]
