# Generated by Django 4.1.2 on 2022-10-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_quote_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
    ]
