# Generated by Django 4.1.2 on 2022-12-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_quote_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='expitation_date',
            new_name='expiration_date',
        ),
    ]
