# Generated by Django 4.1.2 on 2023-05-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1121, max_length=128, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
